#!/bin/bash
set -e

echo "=========================================="
echo "Squid Proxy Auto-Installation Script"
echo "For Ubuntu 22.04 LTS"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "❌ Please run as root (use sudo)"
    exit 1
fi

# Check Ubuntu version
if ! grep -q "22.04" /etc/os-release 2>/dev/null; then
    echo "⚠️  Warning: This script is designed for Ubuntu 22.04"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo "🔄 Updating package lists..."
apt-get update -qq

echo "📦 Installing Squid and required packages..."
DEBIAN_FRONTEND=noninteractive apt-get install -y squid apache2-utils

echo "✅ Squid installed successfully"
echo ""

# Stop Squid for configuration
systemctl stop squid

# Generate random credentials
PROXY_USERNAME="squid_proxy"
PROXY_PASSWORD=$(openssl rand -base64 16 | tr -d "=+/" | cut -c1-16)
PROXY_PORT=3128
SERVER_IP=$(hostname -I | awk '{print $1}')

echo "🔑 Generating proxy credentials..."
echo "   Username: $PROXY_USERNAME"
echo "   Password: $PROXY_PASSWORD"
echo ""

# Create password file
htpasswd -bc /etc/squid/passwd "$PROXY_USERNAME" "$PROXY_PASSWORD"
chmod 640 /etc/squid/passwd
chown root:proxy /etc/squid/passwd

echo "✅ Credentials created and secured"
echo ""

# Backup original config
cp /etc/squid/squid.conf /etc/squid/squid.conf.backup.$(date +%Y%m%d_%H%M%S)

# Create new Squid configuration
cat > /etc/squid/squid.conf <<'EOF'
# Squid Proxy Configuration
# Auto-generated by installation script

# Authentication
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
auth_param basic children 5
auth_param basic realm Squid Proxy Server
auth_param basic credentialsttl 2 hours

# Proxy port
http_port 3128

# Access Control Lists (ACLs)
acl authenticated proxy_auth REQUIRED
acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

# SSL/Safe ports
acl SSL_ports port 443
acl Safe_ports port 80          # HTTP
acl Safe_ports port 21          # FTP
acl Safe_ports port 443         # HTTPS
acl Safe_ports port 70          # Gopher
acl Safe_ports port 210         # WAIS
acl Safe_ports port 1025-65535  # Unregistered ports
acl Safe_ports port 280         # HTTP-mgmt
acl Safe_ports port 488         # GSS-HTTP
acl Safe_ports port 591         # FileMaker
acl Safe_ports port 777         # Multiling HTTP

acl CONNECT method CONNECT

# Access rules
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access allow localhost
http_access allow authenticated
http_access deny all

# Cache settings
cache_dir ufs /var/spool/squid 100 16 256
cache_mem 256 MB
maximum_object_size 4096 KB
minimum_object_size 0 KB

# Refresh patterns
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320

# Logging
access_log daemon:/var/log/squid/access.log squid
cache_log /var/log/squid/cache.log
cache_store_log /var/log/squid/store.log

# DNS
dns_nameservers 8.8.8.8 8.8.4.4 1.1.1.1

# Forwarded headers
forwarded_for on
via on

# Misc settings
coredump_dir /var/spool/squid
refresh_pattern . 0 20% 4320
EOF

echo "✅ Squid configuration created"
echo ""

# Initialize Squid cache
echo "🔄 Initializing Squid cache directories..."
squid -z 2>/dev/null || true
sleep 2

# Start and enable Squid
echo "🚀 Starting Squid service..."
systemctl enable squid
systemctl start squid

# Wait for Squid to start
sleep 3

# Check if Squid is running
if systemctl is-active --quiet squid; then
    echo "✅ Squid is running"
else
    echo "❌ Failed to start Squid"
    echo "Check logs: journalctl -u squid -n 50"
    exit 1
fi

# Configure firewall (if UFW is available)
if command -v ufw &> /dev/null; then
    echo ""
    echo "🔥 Configuring firewall (UFW)..."
    ufw allow $PROXY_PORT/tcp comment 'Squid Proxy' 2>/dev/null || true
    echo "✅ Firewall rule added for port $PROXY_PORT"
fi

# Test proxy authentication
echo ""
echo "🧪 Testing proxy configuration..."
sleep 2

if curl -x http://$PROXY_USERNAME:$PROXY_PASSWORD@localhost:$PROXY_PORT http://httpbin.org/ip -s -o /dev/null -w "%{http_code}" | grep -q "200"; then
    echo "✅ Proxy authentication test passed"
else
    echo "⚠️  Proxy test returned non-200 status (this may be normal)"
fi

# Save credentials to file
CREDENTIALS_FILE="/root/squid-proxy-credentials.txt"
cat > $CREDENTIALS_FILE <<EOF
========================================
Squid Proxy Credentials
========================================
Server IP:    $SERVER_IP
Proxy Port:   $PROXY_PORT
Protocol:     HTTP
Username:     $PROXY_USERNAME
Password:     $PROXY_PASSWORD

Connection String:
http://$PROXY_USERNAME:$PROXY_PASSWORD@$SERVER_IP:$PROXY_PORT

cURL Test Command:
curl -x http://$PROXY_USERNAME:$PROXY_PASSWORD@$SERVER_IP:$PROXY_PORT http://httpbin.org/ip

Configuration Files:
- Main config:     /etc/squid/squid.conf
- Password file:   /etc/squid/passwd
- Access log:      /var/log/squid/access.log
- Cache log:       /var/log/squid/cache.log

Useful Commands:
- Check status:    systemctl status squid
- Restart:         systemctl restart squid
- View logs:       tail -f /var/log/squid/access.log
- Test config:     squid -k parse

To add more users:
htpasswd -b /etc/squid/passwd <username> <password>
systemctl restart squid

Generated: $(date)
========================================
EOF

chmod 600 $CREDENTIALS_FILE

echo ""
echo "=========================================="
echo "✅ Installation Complete!"
echo "=========================================="
echo ""
echo "📋 Proxy Details:"
echo "   Server IP:    $SERVER_IP"
echo "   Port:         $PROXY_PORT"
echo "   Protocol:     HTTP"
echo "   Username:     $PROXY_USERNAME"
echo "   Password:     $PROXY_PASSWORD"
echo ""
echo "🔗 Connection String:"
echo "   http://$PROXY_USERNAME:$PROXY_PASSWORD@$SERVER_IP:$PROXY_PORT"
echo ""
echo "📄 Credentials saved to: $CREDENTIALS_FILE"
echo ""
echo "🧪 Test with cURL:"
echo "   curl -x http://$PROXY_USERNAME:$PROXY_PASSWORD@$SERVER_IP:$PROXY_PORT http://httpbin.org/ip"
echo ""
echo "📊 Check status:"
echo "   systemctl status squid"
echo ""
echo "📝 View access logs:"
echo "   tail -f /var/log/squid/access.log"
echo ""
echo "=========================================="
